version: "3"
services:
  # this container will run Cypress test using built-in Electron browser
  e2e-electron:
    image: "ramzes-cypress-js"
    command: "test"
    volumes:
      - ./cypress/videos:/ramzes-cypress-js/cypress/videos
      - ./cypress/reports:/ramzes-cypress-js/cypress/reports

  # this container will run Cypress test using Chrome browser
  e2e-chrome:
    image: "ramzes-cypress-js"
    command: "test-chrome"
    volumes:
      - ./cypress/videos:/ramzes-cypress-js/cypress/videos
      - ./cypress/reports:/ramzes-cypress-js/cypress/reports

  # this container will run Cypress test using Firefox browser
  # note that both Chrome and Firefox browsers were pre-installed in the Docker image
  e2e-firefox:
    image: "ramzes-cypress-js"
    command: "test-firefox"
    # if you want to debug FF run, pass DEBUG variable like
    environment:
      - DEBUG=cypress:server:browsers:firefox-util,cypress:server:util:process_profiler
    volumes:
      - ./cypress/videos:/ramzes-cypress-js/cypress/videos
      - ./cypress/reports:/ramzes-cypress-js/cypress/reports